use std::io::Error as IOError;

pub fn main() -> Result<(), IOError> {
    unimplemented!()
}
